stages:
  - build
  - deploy

variables:
  PORT: "3000"
  APP_DIR: "/$HOST_USER/stay_connected"
  DOCKER_IMAGE: "stay_connected:latest"

.default-before-script: &default-before-script
  - eval $(ssh-agent -s)
  - chmod 400 "$STAGING_AREA_PRIVATE_KEY"
  - ssh-add "$STAGING_AREA_PRIVATE_KEY"
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan $APP_HOST >> ~/.ssh/known_hosts

build:
  stage: build
  before_script:
    <<: *default-before-script
  script:
    - ssh $HOST_USER@$APP_HOST "rm -rf $APP_DIR && mkdir -p $APP_DIR"
    - tar --exclude='.git' --exclude='node_modules' -czf app.tar.gz .
    - scp app.tar.gz $HOST_USER@$APP_HOST:$APP_DIR
    - ssh $HOST_USER@$APP_HOST "cd $APP_DIR && tar -xzf app.tar.gz && rm -f app.tar.gz"
    - ssh $HOST_USER@$APP_HOST "cd $APP_DIR && docker build -t stay_connected:latest ."

deploy:
  stage: deploy
  before_script:
    <<: *default-before-script
  script:
    - ssh $HOST_USER@$APP_HOST "docker stop stay_connected || true && docker rm stay_connected || true"
    - ssh $HOST_USER@$APP_HOST "docker run -d --name stay_connected -p $PORT:$PORT stay_connected:latest"
  environment:
    name: production
